baseURL = "https://zeyaddeeb.com/"
languageCode = "en-us"
title = "Zeyad Deeb"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4 
summaryLength = 20
googleAnalytics = "UA-76463767-1"


[author]
    name = "Zeyad Deeb"

[params]
  description = "The statistical brick road"
  linkedin = "https://www.linkedin.com/in/zeyaddeeb"
  github = "https://github.com/zeyaddeeb"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    style = "friendly"

[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1

